export const GET_JOBS = "GET_JOBS";
export const ERROR_GET_JOBS = "ERROR_GET_JOBS";

// export const REPORTS_PAGE = "REPORTS_PAGE";
// export const ERROR_REPORTS_PAGE = "ERROR_REPORTS_PAGE";

export const GET_METADATA = "GET_METADATA";
export const ERROR_GET_METADATA = "ERROR_GET_METADATA";

export const POST_UNSERINPUT = "POST_UNSERINPUT";
export const ERROR_POST_UNSERINPUT = "ERROR_POST_UNSERINPUT";
